import "./globals.css";
import { Rubik } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
// components
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Help Desk App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
