import { Rubik } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
const rubik = Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Dashboard Admin MainLaptop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {" "}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
